FROM jupyter/r-notebook:45bfe5a474fa
# Digest 6b358dee6a30
# This is the most recent on 20201026 (pushed 6 days ago, has the "latest" tag).

# Version 20201026

COPY ./favicon.ico /opt/conda/lib/python3.8/site-packages/notebook/static/base/images/favicon.ico

# docker build -t jupyter/r-notebook:45bfe5a474fa-20201026 .
# docker build -t registry-sdc.argo.grnet.gr/jupyter/r-notebook:45bfe5a474fa-20201026 .
# docker push registry-sdc.argo.grnet.gr/jupyter/r-notebook:45bfe5a474fa-20201026

