version: '3.3'

services:

  nginx:
    image: nginx
    networks:
      - deltares
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../HEALTH/healthcheck_nginx.sh:/bin/healthcheck.sh
    ports:
      - "80" # nginx is exposed to 8003 outside
    depends_on:
      - rest
      - static
    command: [nginx-debug, '-g', 'daemon off;']
    healthcheck:
      test: ["CMD", "/bin/healthcheck.sh"]
      interval: 60s
      timeout: 30s
      retries: 5

  rest:
    image: registry-sdc.argo.grnet.gr/sdc-visualization-service:build-2020-05-22T1951
    volumes:
      - /var/viz_data/public:/data/public
      - /home/vre/nextcloud_data/:/data/user
      - work:/data/work
    networks:
      - deltares
    restart: always

  static:
    image: registry-sdc.argo.grnet.gr/sdc-visualization-static:build-2020-06-23T1349
    volumes:
      - /var/viz_data/public/climatology/:/usr/share/nginx/html/models
    networks:
      - deltares
    restart: always

networks:
  deltares:
    driver: "bridge"

volumes:
  storage:
    driver: local
  work:
    driver: local
