version: '3.3'

services:

  nginx_deltares:
    image: nginx
    restart: always
    volumes:
      - ./nginx-deltares.conf:/etc/nginx/conf.d/default.conf
      - ../HEALTH/healthcheck_nginx.sh:/bin/healthcheck.sh
      - ../SECURITY/ssl/certs/cert_and_chain.crt:/etc/ssl/certs/myhost.crt:ro
      - ../SECURITY/ssl/private/priv.key:/etc/ssl/private/myhost.key:ro
    ports:
      - "8003:443" # nginx is exposed to 8003 outside
    networks:
      - vre-dev
    depends_on:
      - rest
      - static
    healthcheck:
      test: ["CMD", "/bin/healthcheck.sh"]
      interval: 60s
      timeout: 30s
      retries: 5

  rest:
    image: openearth/sdc-visualization-service
    restart: always
    ports:
      - "5000" # no exposure to outside, no SSL (nginx handles that)
    networks:
      - vre-dev

  static:
    image: openearth/sdc-visualization-static
    restart: always
    ports:
      - "80" # no exposure to outside, no SSL (nginx handles that)
    networks:
      - vre-dev
    environment:
      # 1. Does the service run behind a reverse proxy?
      # If , makes sure that the FORCE_ROOT_URL is used in all HTML links,
      # HTML forms etc. (served by Laravel) if service runs behind a
      # reverse proxy, i.e. forceRootUrl() is enforced in Laravel.
      # Please use 1 for true and 0 for false!
      REVERSE_PROXY: 1 # 1=true!
      #
      # 2. This URL is used in HTML links, HTML forms etc. (served by
      # Laravel) if service runs behind a reverse proxy, i.e. forceRootUrl()
      # is enforced in Laravel.
      # Please include the protocol, i.e. "https://".
      # Note: Only used if REVERSE_PROXY is true.
      FORCE_ROOT_URL: 'https://xxx.xxx.xx:8003'
      # 
      # 3. This makes sure that https is used in HTML links, HTML forms etc.
      # (served by Laravel) if service runs behind a reverse proxy, i.e.
      # forceScheme() is enforced in Laravel.
      # Note: Only used if REVERSE_PROXY is true.
      FORCE_SCHEME: 'https'
      #
      # 4. URL of the file selector
      FILE_SELECTOR_URL: "https://xxx.xxx.xx:8003/webdav-fileselector"


networks:
  vre-dev:
    external: true

