version: '3.3'

services:
  fileselector:
   image: registry-sdc.argo.grnet.gr/vre_fileselector:20200424-4
   expose:
    - 80
   volumes:
    - /nfs-export:/var/www/html/fileselector/storage/app/data
   networks:
    - vre_proxy
   environment:
    dashboard_url: dashboard # this is needed for the service_auth                                                                     
    FORCE_ROOT_URL: 'http://sdc-test.argo.grnet.gr/fileselector'
    FORCE_SCHEME: 'https'

networks:
   vre_proxy:
     external: true

