version: '3.3'
services:
  fileselector:
   image: registry-sdc.argo.grnet.gr/vre_fileselector:20200424-4
   expose:
    - 80
   volumes:
    - /nfs-export:/var/www/html/fileselector/storage/app/data
   networks:
    - vre_dash
   environment:
    dashboard_url: vrehome_dashboard_1 # this is needed for the service_auth                                                                     
    FORCE_ROOT_URL: 'http://sdc-test.argo.grnet.gr:7788'
    FORCE_SCHEME: 'https'

  #############
  ### nginx ###
  #############
  proxy_for_fileselector:
    image: nginx
    restart: always
    volumes:
      - ./nginx_fileselector.conf:/etc/nginx/conf.d/default.conf
      - /root/HEALTH/healthcheck_nginx.sh:/bin/healthcheck.sh
      - /root/cert/cert.pem:/etc/ssl/certs/myhost.crt:ro
      - /root/cert/cert.key:/etc/ssl/private/myhost.key:ro
    ports:
      - "7788:443"
    networks:
      - vre_dash
    depends_on:
      - fileselector 
    healthcheck:
      test: ["CMD", "/bin/healthcheck.sh"]
      interval: 60s
      timeout: 30s
      retries: 5

networks:
   vre_dash:
     external: true

