version: '2'

services:
  fileselector:
   image: registry-sdc.argo.grnet.gr/fileselector:20191206-1
   #ports:
   # - 7788:80
   volumes:
    - /srv/seadata/vre/sync:/var/www/html/fileselector/storage/app/data
   networks:
    - vre
   environment:
    dashboard_url: https://manatee.gr # this is needed for the service_auth
    FORCE_SCHEME: 'https'

  proxy_for_fileselector:
    image: nginx
    restart: always
    volumes:
      - ./nginx_fileselector.conf:/etc/nginx/conf.d/default.conf
      - ../HEALTH/healthcheck_nginx.sh:/bin/healthcheck.sh
      - /path/to/ssl/certs/cert_and_chain.crt:/etc/ssl/certs/myhost.crt:ro
      - /path/to/ssl/private/priv.key:/etc/ssl/private/myhost.key:ro
    ports:
      - "7788:443"
    networks:
      - vre
    depends_on:
      - fileselector
    healthcheck:
      test: ["CMD", "/bin/healthcheck.sh"]
      interval: 60s
      timeout: 30s
      retries: 5


networks:
   vre:
     external: true
