version: '2'
services:
  fileselector:
   image: registry-sdc.argo.grnet.gr/fileselector:20191106-1
   ports:
    - 7788:80
   volumes:
    - /srv/seadata/vre/sync:/var/www/html/fileselector/storage/app/data
   networks:
    - vre
   environment:
    dashboard_url: https://manatee.gr # this is needed for the service_auth                                                                     
networks:
   vre:
     external: true
