version: '3.3'

services:

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../HEALTH/healthcheck_nginx.sh:/bin/healthcheck.sh
      - ../SECURITY/ssl/certs/cert_and_chain.crt:/etc/ssl/certs/myhost.crt:ro
      - ../SECURITY/ssl/certs/private:/etc/ssl/private/myhost.key:ro
      - ./favicon-32x32.png:/etc/nginx/html/favicon.ico
    ports:
      - "443:443"
      - 80:80
    networks:
       - vre
    healthcheck:
      test: ["CMD", "/bin/healthcheck.sh"]
      interval: 60s
      timeout: 30s
      retries: 5

networks:
  vre:
    external: true


