version: '3.3'

services:

  nginx:
    image: nginx # TODO fix version!
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /root/HEALTH/healthcheck_nginx.sh:/bin/healthcheck.sh
      - /root/SECURITY/ssl/certs/cert_and_chain.crt:/etc/ssl/certs/myhost.crt:ro
      - /root/SECURITY/ssl/certs/private:/etc/ssl/private/myhost.key:ro
      - ./favicon-32x32.png:/etc/nginx/html/favicon.ico
    ports:
      - 443:443
      - 80:80
    networks:
       - vre_proxy
    healthcheck:
      test: ["CMD", "/bin/healthcheck.sh"]
      interval: 60s
      timeout: 30s
      retries: 5

networks:
  vre_proxy:
    external: true


