version: '3.3'

services:

  nginx:
    image: nginx:1.19.2
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./odv_html:/srv/odv  # TODO What for?
      - ../HEALTH/healthcheck_nginx.sh:/bin/healthcheck.sh
      - ../SECURITY/ssl/certs/star.argo.grnet.gr.crt:/etc/ssl/certs/myhost.crt:ro
      - ../SECURITY/ssl/certs/star.argo.grnet.gr.key:/etc/ssl/private/myhost.key:ro
      - ./favicon-32x32.png:/etc/nginx/html/favicon.ico
    ports:
      - 443:443
      - 80:80
    networks:
       - vre_proxy
    healthcheck:
      test: ["CMD", "/bin/healthcheck.sh"]
      interval: 60s
      timeout: 30s
      retries: 5

networks:
  vre_proxy:
    external: true

