version: '3.3'

services:

  # PROXY:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx_proxy.conf:/etc/nginx/conf.d/default.conf
      - /path/to/healthcheck_nginx.sh:/bin/healthcheck.sh
      - /path/to/ssl/certs/cert_and_chain.crt:/etc/ssl/certs/myhost.crt:ro
      - /path/to/ssl/private/priv.key:/etc/ssl/private/myhost.key:ro
    ports:
      - "8191:443"
    networks:
      - vre
    depends_on:
      - webodv
    healthcheck:
      test: ["CMD", "/bin/healthcheck.sh"]
      interval: 60s
      timeout: 30s
      retries: 5

  webodv:
   image: registry-sdc.argo.grnet.gr/vre_odv:20191210-1
   restart: always
   depends_on:
    - db_odv
   ports:
    - "80"
   volumes:
       # ODV installation
       - ./odv_5.1.7beta_linux-amd64_ubuntu-18.04:/var/www/html/odv_software:ro
       # ODV bathy data
       - ./ODV:/home/woody/Documents/ODV:rw
       # webODV settings
       - ./settings_webodv:/var/www/html/webodv/storage/app:rw
       # vre mount
       - /path/to/your/sync/target:/var/www/html/webodv/storage/nc_sync
   networks:
    - vre
   environment:
    # 1. Does the service run behind a reverse proxy?
    # If , makes sure that the FORCE_ROOT_URL is used in all HTML links,
    # HTML forms etc. (served by Laravel) if service runs behind a
    # reverse proxy, i.e. forceRootUrl() is enforced in Laravel.
    # Please use 1 for true and 0 for false!
    REVERSE_PROXY: 1 # 1=true!
    #
    # 2. This URL is used in HTML links, HTML forms etc. (served by
    # Laravel) if service runs behind a reverse proxy, i.e. forceRootUrl()
    # is enforced in Laravel.
    # Please include the protocol, i.e. "https://".
    # Note: Only used if REVERSE_PROXY is true.
    FORCE_ROOT_URL: 'https://xxxxx.xxx.xx:8191'
    # 
    # 3. This makes sure that https is used in HTML links, HTML forms etc.
    # (served by Laravel) if service runs behind a reverse proxy, i.e.
    # forceScheme() is enforced in Laravel.
    # Note: Only used if REVERSE_PROXY is true.
    FORCE_SCHEME: 'https'
    #
    # 4. Dashboard URL, for authentication: ODV asks this URL for token
    # verification.
    DASHBOARD_URL: 'https://dashboard.argo.grnet.gr'
   labels:
     - "webODV in VRE"
   healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:80/webodv"]
    interval: 60s
    timeout: 30s
    retries: 5

  db_odv:
   image: mysql/mysql-server:8.0.0
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: XXXX  # please adapt!
    MYSQL_DATABASE: XXXXX      # please adapt!
    MYSQL_USER: XXXX           # please adapt!
    MYSQL_PASSWORD: XXXXX      # please adapt!
   networks:
    - vre
   volumes:
    - ./mysql_data_persistent:/var/lib/mysql
   healthcheck:
    test: "/usr/bin/mysql --user=XXXXX --password=XXXXX --silent --execute \"SELECT 1;\"" #please adapt!
    interval: 30s
    timeout: 10s
    retries: 5

networks:
  vre:
    external: true